apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
spec:
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
      - name: apigateway
        image: jarvis-master:32000/apigateway
        # This will make sure that the local image is used
        # imagePullPolicy: Never
        ports:
        - containerPort: 80
      nodeSelector:
        apig: jarvis-master

---
apiVersion: v1
kind: Service
metadata:
  name: apigateway
spec:
  # This is for local testing this will expose
  # service on a NAT'ed port
  type: NodePort
  ports:
  - name: apigatewayports
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30000
  selector:
    app: apigateway
