# Deploying database
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  ports:
  - name: mongodbports
    protocol: TCP
    port: 27017
    targetPort: 27017
  selector:
    app: mongodb

---
# App server deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authserver
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: authserver
  template:
    metadata:
      labels:
        app: authserver
    spec:
      containers:
      - name: authserver
        image: jarvis-master:32000/authserver
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: authserver
spec:
  ports:
  - name: authserverports
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: authserver
