apiVersion: apps/v1
kind: Deployment
metadata:
  name: cacheserver
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: cacheserver
  template:
    metadata:
      labels:
        app: cacheserver
    spec:
      containers:
      - name: cacheserver
        image: jarvis-master:32000/cacheserver
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: cacheserver
spec:
  ports:
  - name: cacheserverports
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: cacheserver
