# Deploying database
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        app: postgresdb
    spec:
      containers:
      - name: postgresdb
        image: jarvis-master:32000/postgresdb
        imagePullPolicy: Always
        # This will make sure that the local image is used
        # imagePullPolicy: Never
        ports:
        - containerPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: postgresdb
spec:
  # This is for local testing this will expose
  # service on a NAT'ed port
  # type: NodePort
  ports:
  - name: postgresdbports
    protocol: TCP
    port: 5432
    targetPort: 5432
  selector:
    app: postgresdb

---
# Deploying java application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbapp
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
  replicas: 2
  selector:
    matchLabels:
      app: dbapp
  template:
    metadata:
      labels:
        app: dbapp
    spec:
      containers:
      - name: dbapp
        image: jarvis-master:32000/dbapp
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: dbapp
spec:
  ports:
  - name: dbappports
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: dbapp
