# Deploying database
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  # This is for local testing this will expose
  # service on a NAT'ed port
  # type: NodePort
  ports:
  - name: mongodbports
    protocol: TCP
    port: 27017
    targetPort: 27017
  selector:
    app: mongodb

---
# App server deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: authserver
  template:
    metadata:
      labels:
        app: authserver
    spec:
      containers:
      - name: authserver
        image: authserver
        # This will make sure that the local image is used
        imagePullPolicy: Never
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: authserver
spec:
  # This is for local testing this will expose
  # service on a NAT'ed port
  # type: NodePort
  ports:
  - name: authserverports
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: authserver


