version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8088:8088
    depends_on:
      - postgresdb
  postgresdb:
    image: "postgres:11.4"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - "./ads_workingv1.3.sql:/docker-entrypoint-initdb.d/test.sql"
